const ENGLISH_SHARED_STRINGS = {
  actions: {
    add: "Add",
    archive: "Archive",
    cancel: "Cancel",
    clear: "Clear",
    close: "Close",
    confirm: "Confirm",
    create: "Create",
    delete: "Delete",
    edit: "Edit",
    filter: "Filter",
    open: "Open",
    restore: "Restore",
    retry: "Retry",
    save: "Save",
    search: "Search",
    update: "Update",
  },
  fields: {
    amount: "Amount",
    date: "Date",
    fromDate: "From date",
    name: "Name",
    note: "Note",
    noteOptional: "Note (optional)",
    status: "Status",
    toDate: "To date",
  },
  payment: {
    amount: "Payment amount",
    date: "Payment date",
    mode: "Payment mode",
    modes: "Payment modes",
    addSplit: "Add split",
    removeSplit: "Remove split",
    selectMode: "Select mode",
    history: "Payment history",
    outstanding: "Outstanding",
    due: "Due",
    loadingHistory: "Loading payment history...",
    historyLoadError: "Could not load payment history.",
    noHistory: "No payments recorded yet.",
  },
  feedback: {
    loading: "Loading...",
    saving: "Saving...",
    unavailable: "Unavailable",
  },
  dashboard: {
    cashBookNotStarted: "Cash Book not started",
    cashBookSetupDescription: "Open Cash Book to complete its one-time setup.",
  },
  auth: {
    loginTitle: "Welcome back",
    loginDescription: "Log in to your Atlas workspace.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    showPassword: "Show password",
    hidePassword: "Hide password",
    login: "Log in",
    loggingIn: "Logging in...",
    newToAtlas: "New to Atlas?",
    createAccount: "Create account",
    invalidCredentials: "Email or password is incorrect.",
    workspaceError: "Unable to verify your workspace. Please try again.",
    signupTitle: "Create your account",
    signupDescription: "Set up your Atlas login to get started.",
    confirmPassword: "Confirm password",
    passwordHelp: "Use at least 12 characters.",
    emailRequired: "Email is required.",
    emailInvalid: "Enter a valid email address.",
    passwordRequired: "Password is required.",
    passwordTooShort: "Password must be at least 12 characters.",
    passwordMismatch: "Passwords do not match.",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    signupError: "Unable to create your account. Please try again.",
    signupConfigurationError: "Email verification is unavailable. Please contact support.",
    verifyTitle: "Verify your email",
    verifyDescription: "Enter the code we sent to",
    verificationCode: "Verification code",
    verifyEmail: "Verify email",
    verifyingEmail: "Verifying email...",
    otpRequired: "Enter the complete verification code.",
    otpInvalid: "The code is incorrect or has expired.",
    verificationError: "Unable to verify your email. Please try again.",
    didntReceiveCode: "Didn't receive the code?",
    resendCode: "Resend code",
    resendingCode: "Sending code...",
    resendAvailableIn: "Resend available in",
    resendError: "Unable to send a new code yet. Please wait and try again.",
    resendSuccess: "A new code was sent. Use the newest code.",
    wrongEmail: "Wrong email?",
    changeEmail: "Change email",
    missingEmailDescription: "Enter the email address you used to create your account.",
    continueToVerification: "Continue",
    checkingVerification: "Checking verification details...",
    onboardingTitle: "Set up your factory",
    onboardingDescription: "Enter the factory name your team uses day to day.",
    factoryName: "Factory name",
    factoryNamePlaceholder: "e.g. Shree Kiln Industries",
    factoryNameRequired: "Factory name is required.",
    factoryNameTooLong: "Factory name must be 200 characters or fewer.",
    factoryNameInvalid: "Check the factory name and try again.",
    createFactory: "Create factory",
    creatingFactory: "Creating factory...",
    factoryCreateError: "We couldn't create your factory. Try again.",
    checkingAccount: "Checking your account...",
    accessDisabledTitle: "Account access disabled",
    accessDisabledDescription: "Your account is signed in, but access to this factory is currently disabled.",
    accessDisabledHelp: "Contact the person who manages this account to restore access.",
    logout: "Log out",
    loggingOut: "Signing out...",
    logoutError: "Could not sign out. Please try again.",
    forgotPasswordTitle: "Forgot your password?",
    forgotPasswordDescription: "Enter your email and we'll send you a recovery code.",
    sendRecoveryCode: "Send reset code",
    sendingRecoveryCode: "Sending code...",
    recoveryRequestSuccess: "If an account can use this email, we sent a password reset code.",
    recoveryVerifyTitle: "Enter recovery code",
    recoveryVerifyDescription: "Enter the recovery code for",
    recoveryCode: "Recovery code",
    verifyRecoveryCode: "Verify code",
    verifyingRecoveryCode: "Verifying...",
    recoveryOtpInvalid: "The code is incorrect or has expired.",
    recoveryResendError: "Unable to send a new code yet. Please wait and try again.",
    recoveryMissingEmail: "Enter the email address you want to recover.",
    recoverySessionError: "This recovery session is unavailable or expired. Start recovery again.",
    checkingRecovery: "Checking recovery details...",
    newPasswordTitle: "Set a new password",
    newPasswordDescription: "Choose a new password for your Atlas account.",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    resetPassword: "Reset password",
    resettingPassword: "Resetting password...",
    passwordUpdateError: "Unable to update your password. Please try again.",
    recoverySignOutError: "Atlas could not safely end this recovery session. Please try again.",
    restartRecovery: "Start recovery again",
    passwordUpdated: "Password updated. Log in with your new password.",
    backToLogin: "Back to login",
  },
} as const;

type WidenStringLeaves<TValue> = {
  readonly [Key in keyof TValue]: TValue[Key] extends string
    ? string
    : WidenStringLeaves<TValue[Key]>;
};

/**
 * Shape for future language dictionaries. This is intentionally only a typed
 * string structure, not a locale loader or runtime localization framework.
 */
export type AtlasSharedStrings = WidenStringLeaves<
  typeof ENGLISH_SHARED_STRINGS
>;

/** Canonical English wording shared across unrelated Atlas features. */
export const ATLAS_UI_STRINGS: AtlasSharedStrings = ENGLISH_SHARED_STRINGS;
