import type { Config } from "tailwindcss";

const atlasColor = (token: string) => `rgb(var(${token}) / <alpha-value>)`;

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        atlas: {
          background: atlasColor("--atlas-color-background"),
          "background-muted": atlasColor("--atlas-color-background-muted"),
          surface: atlasColor("--atlas-color-surface"),
          "surface-muted": atlasColor("--atlas-color-surface-muted"),
          "surface-hover": atlasColor("--atlas-color-surface-hover"),
          "surface-disabled": atlasColor("--atlas-color-surface-disabled"),
          text: atlasColor("--atlas-color-text"),
          "text-muted": atlasColor("--atlas-color-text-muted"),
          "text-subtle": atlasColor("--atlas-color-text-subtle"),
          "text-disabled": atlasColor("--atlas-color-text-disabled"),
          "text-inverse": atlasColor("--atlas-color-text-inverse"),
          border: atlasColor("--atlas-color-border"),
          "border-strong": atlasColor("--atlas-color-border-strong"),
          primary: atlasColor("--atlas-color-primary"),
          "primary-hover": atlasColor("--atlas-color-primary-hover"),
          "primary-surface": atlasColor("--atlas-color-primary-surface"),
          "primary-border": atlasColor("--atlas-color-primary-border"),
          "primary-foreground": atlasColor("--atlas-color-primary-foreground"),
          accent: atlasColor("--atlas-color-accent"),
          "accent-hover": atlasColor("--atlas-color-accent-hover"),
          "accent-surface": atlasColor("--atlas-color-accent-surface"),
          "accent-border": atlasColor("--atlas-color-accent-border"),
          "accent-foreground": atlasColor("--atlas-color-accent-foreground"),
          success: atlasColor("--atlas-color-success"),
          "success-surface": atlasColor("--atlas-color-success-surface"),
          "success-border": atlasColor("--atlas-color-success-border"),
          "success-text": atlasColor("--atlas-color-success-text"),
          warning: atlasColor("--atlas-color-warning"),
          "warning-surface": atlasColor("--atlas-color-warning-surface"),
          "warning-border": atlasColor("--atlas-color-warning-border"),
          "warning-text": atlasColor("--atlas-color-warning-text"),
          danger: atlasColor("--atlas-color-danger"),
          "danger-surface": atlasColor("--atlas-color-danger-surface"),
          "danger-border": atlasColor("--atlas-color-danger-border"),
          "danger-text": atlasColor("--atlas-color-danger-text"),
          info: atlasColor("--atlas-color-info"),
          "info-surface": atlasColor("--atlas-color-info-surface"),
          "info-border": atlasColor("--atlas-color-info-border"),
          "info-text": atlasColor("--atlas-color-info-text"),
          archive: atlasColor("--atlas-color-archive"),
          "archive-surface": atlasColor("--atlas-color-archive-surface"),
          "archive-border": atlasColor("--atlas-color-archive-border"),
          "archive-text": atlasColor("--atlas-color-archive-text"),
          focus: atlasColor("--atlas-color-focus"),
        },
      },
      spacing: {
        "atlas-0": "var(--atlas-space-0)",
        "atlas-1": "var(--atlas-space-1)",
        "atlas-2": "var(--atlas-space-2)",
        "atlas-3": "var(--atlas-space-3)",
        "atlas-4": "var(--atlas-space-4)",
        "atlas-5": "var(--atlas-space-5)",
        "atlas-6": "var(--atlas-space-6)",
        "atlas-8": "var(--atlas-space-8)",
        "atlas-10": "var(--atlas-space-10)",
        "atlas-12": "var(--atlas-space-12)",
        "atlas-16": "var(--atlas-space-16)",
      },
      borderRadius: {
        "atlas-control": "var(--atlas-radius-control)",
        "atlas-button": "var(--atlas-radius-button)",
        "atlas-card": "var(--atlas-radius-card)",
        "atlas-dialog": "var(--atlas-radius-dialog)",
        "atlas-pill": "var(--atlas-radius-pill)",
      },
      boxShadow: {
        "atlas-low": "var(--atlas-shadow-low)",
        "atlas-medium": "var(--atlas-shadow-medium)",
        "atlas-high": "var(--atlas-shadow-high)",
        "atlas-focus": "var(--atlas-shadow-focus)",
      },
      fontFamily: {
        atlas: ["var(--atlas-font-sans)"],
      },
      fontSize: {
        "atlas-xs": ["var(--atlas-font-size-xs)", { lineHeight: "var(--atlas-line-height-xs)" }],
        "atlas-sm": ["var(--atlas-font-size-sm)", { lineHeight: "var(--atlas-line-height-sm)" }],
        "atlas-base": ["var(--atlas-font-size-base)", { lineHeight: "var(--atlas-line-height-base)" }],
        "atlas-lg": ["var(--atlas-font-size-lg)", { lineHeight: "var(--atlas-line-height-lg)" }],
        "atlas-xl": ["var(--atlas-font-size-xl)", { lineHeight: "var(--atlas-line-height-xl)" }],
        "atlas-2xl": ["var(--atlas-font-size-2xl)", { lineHeight: "var(--atlas-line-height-2xl)" }],
        "atlas-3xl": ["var(--atlas-font-size-3xl)", { lineHeight: "var(--atlas-line-height-3xl)" }],
      },
      fontWeight: {
        "atlas-regular": "var(--atlas-font-weight-regular)",
        "atlas-medium": "var(--atlas-font-weight-medium)",
        "atlas-semibold": "var(--atlas-font-weight-semibold)",
      },
      letterSpacing: {
        "atlas-wide": "var(--atlas-letter-spacing-wide)",
      },
      ringColor: {
        "atlas-focus": atlasColor("--atlas-color-focus"),
      },
      ringOffsetColor: {
        "atlas-focus": atlasColor("--atlas-color-surface"),
      },
      ringWidth: {
        "atlas-focus": "var(--atlas-focus-ring-width)",
      },
      ringOffsetWidth: {
        "atlas-focus": "var(--atlas-focus-ring-offset)",
      },
    },
  },
  plugins: [],
} satisfies Config;
